name: space_race
description: A classic Space race game using Flame Engine

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flame: ^1.10.0
  cupertino_icons: ^1.0.2
  flame_tiled: 1.18.4
  hive: ^2.2.3
  provider: ^6.1.2
  flutter_carousel_slider: ^1.1.0
  flame_audio: ^1.3.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1

flutter:
  uses-material-design: true
  assets:
    - assets/images/player.png
    - assets/images/bullet.png
    - assets/images/enemy.png
    - assets/images/stars_0.png
    - assets/images/explosion.gif
    - assets/audio/background.mp3
    - assets/audio/bullet.mp3
    - assets/audio/boom.mp3
    - assets/images/background.jpg
    - assets/images/rocket1.png
    - assets/images/rocket2.png
    - assets/images/rocket3.png
    
  fonts:
    - family: BungeeInline
      fonts:
        - asset: assets/fonts/BungeeInline/BungeeInline-Regular.ttf

    - family: Sixtyfour
      fonts:
        - asset: assets/fonts/Sixtyfour/Sixtyfour-Regular.ttf
